### ISSUE TITLE
Can't connect to WebSocket - Gives me 404 not found for /hello/info

### ISSUE THREAD

**Issue by kuldeepkeshwar** [spring-guides/gs-messaging-stomp-websocket#20] opened 2015-01-18 15:20 UTC
I want to test out the SockJS-WebSocket messaging as described here but each time I clicked on the connect button, I kept on getting the frustrating error

GET http://localhost:8080/myapp/hello/info 404 (not found). Whoops! Lost connection to undefined

I thought I must be doing something wrong, but I followed the steps 

Finally, I downloaded the gs-messaging-stomp-websocket directory from the tutorial here, went to complete directory where all the files are, and launched it with mvn spring-boot:run. It launched normally. I went to http://localhost:8080 and clicked on the connect button again, and I got the same frustrating error as above. This time, I didn't change a single thing about the configuration or the code.

So please help me and let me know what I am doing wrong, and how to solve this issue.

copied from : https://github.com/spring-guides/gs-messaging-stomp-websocket/issues/19    as i'm also facing same issue

**Comment by dsyer** [comment] 2015-01-18 17:24
Works for me, and there is no instance of the string "myapp" anywhere in the source code, so I feel like maybe some other app is running on port 8080 for you. Maybe you nee dto share exact steps to reproduce (command line listing or something) and all your platform details.

**Comment by gregturn** [comment] 2015-03-17 20:05
Absent anymore details, I'm closing this issue.

**Closed by gregturn** 2015-03-17 20:05 UTC
