### ISSUE TITLE
Example does not work out of the box

### ISSUE THREAD

**Issue by pksilen** [spring-guides/gs-messaging-stomp-websocket#82] opened 2024-04-16 09:51 UTC
The example does not work without adding CORS.

The following line is not correct:
registry.addEndpoint("...");

It should be, e.g.:
registry.addEndpoint("...").setAllowedOrigins("*")

**Comment by robertmcnees** [comment] 2024-07-29 12:35
Hi @pksilen. Thanks for the issue. I see this as a duplicate of #79. Let's continue the discussion there. I'll close this issue as a duplicate.

**Closed by robertmcnees** 2024-07-29 12:35 UTC
Labels: duplicate
